//Location in EEPROM for each thing we want to store between power cycles
enum eepromLocations {
  LOCATION_I2C_ADDRESS = 0x00,
  LOCATION_INTERRUPTENABLE = 0x01,
  LOCATION_DEVICECONTROL = 0x02,
  LOCATION_MOVE = 0x03,
  LOCATION_MOVE_ENABLENVM = 0x07,
  LOCATION_MAXSPEED = 0x08,
  LOCATION_ACCELERATION = 0x0C,
  LOCATION_SPEED = 0x10,
  LOCATION_SPEED_ENABLENVM = 0x14,
  LOCATION_HOLDCURRENT = 0x15,
  LOCATION_RUNCURRENT = 0x17,
};
